load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_library (
    name = "AAD",
    # srcs = glob(["*.cpp"]),
    srcs = glob(["*.h", "*.hpp"]),
    visibility = ["//visibility:public"],
    deps = [
        "//math_library:math_library",
    ]
)